name: Build spring-boot-wiremock-demo

on:
  push:
    paths:
      - spring-boot-wiremock-demo/**
    branches:
      - '**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring-boot-wiremock-demo
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Test
        run: ./mvnw verify
